version: '3'
services:
  db:
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: aiclinix_development
      POSTGRES_USER: aiclinix
      POSTGRES_PASSWORD: password

  redis:
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - ./tmp/redis:/data
